name: despesas_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  # Adicione aqui seus assets, se houver
   - assets/images/zzz.png
  # - images/a_dot_ham.jpeg

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
          weight: 700
    - family: PlaywriteAR
      fonts:
        - asset: assets/fonts/PlaywriteAR-VariableFont_wght.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
          weight: 700
